### ISSUE TITLE
GT-MP Example?

### ISSUE THREAD

**Issue by eodclan** [AlternateLife/JustAnotherVoiceChat#13]
Is there an example how I install the In GT-MP?

**Comment by FabianLars** [comment]
@eodclan Did you take a look at [https://github.com/AlternateLife/JustAnotherVoiceChat-Server#installation](https://github.com/AlternateLife/JustAnotherVoiceChat-Server#installation) ?

**Comment by Micky5991** [comment]
You can find a basic manual here: 
https://github.com/AlternateLife/JustAnotherVoiceChat-Server/blob/master/docs/installation-gtmp.md

And an example resource with some features ready to go, here: 
https://github.com/AlternateLife/JustAnotherVoiceChat-Server/tree/master/JustAnotherVoiceChat.Server.GTMP.Resource
